services:
  frontend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     VITE_DEBUG: ${VITE_DEBUG:-false}
    # container_name: frontend
    image: frontend
    restart: unless-stopped
    env_file:
      - .env.production
      - .env.production
    environment:
      TZ: ${TZ:-Europe/Moscow}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.tpekollec.ru`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=cloudflare"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/ || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - traefik_traefik

# если хочешь в ту же сеть, что и твой traefik:
networks:
  traefik_traefik:
    external: true