server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 25m;

    # длинный кеш для ассетов
    location /assets/ {
        access_log off;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
        try_files $uri =404;
    }

    location / {
        try_files $uri /index.html;
    }

    error_page 404 /index.html;

    gzip on;
    gzip_comp_level 6;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        text/javascript
        application/x-javascript
        image/svg+xml
        font/woff2;
    gzip_min_length 512;
}