/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarrifsRouteImport } from './routes/tarrifs'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as QuestionsFinishRouteImport } from './routes/questionsFinish'
import { Route as QuestionRouteImport } from './routes/question'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const TarrifsRoute = TarrifsRouteImport.update({
  id: '/tarrifs',
  path: '/tarrifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsFinishRoute = QuestionsFinishRouteImport.update({
  id: '/questionsFinish',
  path: '/questionsFinish',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionRoute = QuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/create': typeof CreateRoute
  '/generate': typeof GenerateRoute
  '/profile': typeof ProfileRoute
  '/question': typeof QuestionRoute
  '/questionsFinish': typeof QuestionsFinishRoute
  '/referral': typeof ReferralRoute
  '/tarrifs': typeof TarrifsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/create': typeof CreateRoute
  '/generate': typeof GenerateRoute
  '/profile': typeof ProfileRoute
  '/question': typeof QuestionRoute
  '/questionsFinish': typeof QuestionsFinishRoute
  '/referral': typeof ReferralRoute
  '/tarrifs': typeof TarrifsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/create': typeof CreateRoute
  '/generate': typeof GenerateRoute
  '/profile': typeof ProfileRoute
  '/question': typeof QuestionRoute
  '/questionsFinish': typeof QuestionsFinishRoute
  '/referral': typeof ReferralRoute
  '/tarrifs': typeof TarrifsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/create'
    | '/generate'
    | '/profile'
    | '/question'
    | '/questionsFinish'
    | '/referral'
    | '/tarrifs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/create'
    | '/generate'
    | '/profile'
    | '/question'
    | '/questionsFinish'
    | '/referral'
    | '/tarrifs'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/create'
    | '/generate'
    | '/profile'
    | '/question'
    | '/questionsFinish'
    | '/referral'
    | '/tarrifs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CreateRoute: typeof CreateRoute
  GenerateRoute: typeof GenerateRoute
  ProfileRoute: typeof ProfileRoute
  QuestionRoute: typeof QuestionRoute
  QuestionsFinishRoute: typeof QuestionsFinishRoute
  ReferralRoute: typeof ReferralRoute
  TarrifsRoute: typeof TarrifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarrifs': {
      id: '/tarrifs'
      path: '/tarrifs'
      fullPath: '/tarrifs'
      preLoaderRoute: typeof TarrifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionsFinish': {
      id: '/questionsFinish'
      path: '/questionsFinish'
      fullPath: '/questionsFinish'
      preLoaderRoute: typeof QuestionsFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question': {
      id: '/question'
      path: '/question'
      fullPath: '/question'
      preLoaderRoute: typeof QuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CreateRoute: CreateRoute,
  GenerateRoute: GenerateRoute,
  ProfileRoute: ProfileRoute,
  QuestionRoute: QuestionRoute,
  QuestionsFinishRoute: QuestionsFinishRoute,
  ReferralRoute: ReferralRoute,
  TarrifsRoute: TarrifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
